<?php

namespace AppBundle\Entity\Repository;

/**
 * RealTimeGpsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealTimeGpsRepository extends \Doctrine\ORM\EntityRepository
{
}
